package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Promote30_Snapshot'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Promote30_Snapshot")) {
    requirements {
        add {
            matches("teamcity.agent.name", "dev(3|7)-agent1", "TEMPLATE_RQ_2")
        }
    }
}
